name = "MedicalImageRegistration"
uuid = "a1b2c3d4-e5f6-7890-abcd-ef1234567890"
authors = ["Dale Black"]
version = "0.1.0"

[deps]
AcceleratedKernels = "6a4ca0a5-0e36-4168-a932-d9be78d558f1"
Atomix = "a9b6321e-bd34-4604-b9c9-b65b8de01458"
Metal = "dde4c033-4e86-420c-a63e-0dd931031962"
Mooncake = "da2b9cff-9c12-43a0-ae48-6db2b0edb7d6"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"

[compat]
AcceleratedKernels = "0.4"
Atomix = "1.1"
Metal = "1.9.2"
Mooncake = "0.5"
StableRNGs = "1.0.4"
julia = "1.10"

[extras]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Metal = "dde4c033-4e86-420c-a63e-0dd931031962"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "PythonCall", "Random", "Metal", "LinearAlgebra", "Statistics", "StableRNGs"]
